# Generated by Django 5.1.3 on 2024-11-29 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curral',
            fields=[
                ('id_curral', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('peso_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacidade_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LocalAplicacaoMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimentacao', models.DateField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=100)),
                ('finalizada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_raca', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sexo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StatusBoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCurral',
            fields=[
                ('id_tipoCurral', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_curral', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_medicamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('curral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boi.curral')),
            ],
        ),
        migrations.CreateModel(
            name='Boi',
            fields=[
                ('id_brinco', models.AutoField(primary_key=True, serialize=False)),
                ('brinco', models.CharField(max_length=15)),
                ('fornecedor', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
                ('data_entrada', models.DateField()),
                ('peso_entrada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('peso_saida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boi.lote')),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boi.raca')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boi.sexo')),
                ('status_boi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boi.statusboi')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('dias_carencia', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('laboratorio', models.CharField(max_length=30)),
                ('local_aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boi.localaplicacaomedicamento')),
                ('tipo_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boi.tipomedicamento')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_manejo', models.DateField()),
                ('boi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boi.boi')),
                ('curral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boi.curral')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boi.lote')),
                ('movimentacao_geral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boi.movimentacaogeral')),
            ],
        ),
        migrations.CreateModel(
            name='PesoAtualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novo_peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pesagem', models.DateField()),
                ('boi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boi.boi')),
            ],
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('doenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boi.doenca')),
            ],
        ),
        migrations.CreateModel(
            name='ProtocoloMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosagem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boi.medicamento')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boi.protocolo')),
            ],
        ),
        migrations.CreateModel(
            name='ProtocoloRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_protocolo_realizado', models.DateField()),
                ('boi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boi.boi')),
                ('protocolo_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boi.protocolomedicamento')),
            ],
        ),
        migrations.AddField(
            model_name='curral',
            name='id_tipoCurral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boi.tipocurral'),
        ),
    ]
