# Generated by Django 5.1.3 on 2024-12-03 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curral',
            fields=[
                ('id_curral', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('peso_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacidade_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id_raca', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_raca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id_sexo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_sexo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StatusBoi',
            fields=[
                ('id_statusboi', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_status', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCurral',
            fields=[
                ('id_tipoCurral', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_curral', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('curral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='boi.curral')),
            ],
        ),
        migrations.CreateModel(
            name='Boi',
            fields=[
                ('id_brinco', models.AutoField(primary_key=True, serialize=False)),
                ('brinco', models.CharField(max_length=15)),
                ('fornecedor', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
                ('data_entrada', models.DateField()),
                ('peso_entrada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('peso_saida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boi_lote', to='boi.lote')),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boi_raca', to='boi.raca')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boi_sexo', to='boi.sexo')),
                ('status_boi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boi_status', to='boi.statusboi')),
            ],
        ),
        migrations.AddField(
            model_name='curral',
            name='curral_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_curral', to='boi.tipocurral'),
        ),
    ]
