# Generated by Django 5.1.3 on 2024-12-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaBoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default='Nova entrada', max_length=255)),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
