# Generated by Django 5.1.3 on 2024-12-03 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boi', '0002_boi_curral_alter_curral_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boi',
            name='curral',
        ),
    ]
