# Generated by Django 5.1.3 on 2024-12-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boi', '0003_remove_doenca_id_remove_entradaboi_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boi',
            name='id_brinco',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='curral',
            name='id_curral',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doenca',
            name='id_doenca',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entradaboi',
            name='id_entrada',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='localaplicacaomedicamento',
            name='id_localaplicacao',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lote',
            name='id_lote',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='id_medicamento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pesoatualizacao',
            name='id_pesoatualizacao',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='id_protocolo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='protocolomedicamento',
            name='id_protocolomedicamento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='protocolorealizado',
            name='id_protocolorealizado',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='raca',
            name='id_raca',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sexo',
            name='id_sexo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='statusboi',
            name='id_statusboi',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipocurral',
            name='id_tipoCurral',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipomedicamento',
            name='id_tipomedicamento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
