# Generated by Django 5.1.3 on 2024-12-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boi', '0006_alter_boi_brinco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boi',
            name='brinco',
            field=models.CharField(max_length=15),
        ),
    ]
